//! Exercise sources, solutions and `info.toml` compiled into the binary.
//! The file list is generated by `build.rs`.

pub struct EmbeddedFile {
    pub path: &'static str,
    pub content: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/embedded_files.rs"));

pub const INFO_TOML: &str = include_str!("../info.toml");

/// Look up an embedded file by its path relative to the exercise directory
/// root, e.g. `exercises/00_intro/intro1.c`.
pub fn get(path: &str) -> Option<&'static str> {
    let path = path.replace('\\', "/");
    EMBEDDED_FILES
        .iter()
        .find(|f| f.path == path)
        .map(|f| f.content)
}
